import { Skeleton, SkeletonText, Table, TableContainer, Tbody, Td, Th, Thead, Tr } from "@chakra-ui/react";
import { Fragment } from "react";

export function SkeletonLista(){
  return (
    <Fragment>
    
    <TableContainer>
      <Table variant='simple'>
        <Thead>
          <Tr>
            <Th>Funcionário</Th>
            <Th>Status</Th>
            <Th>Alteração</Th>
            <Th></Th>
          </Tr>
        </Thead>
        <Tbody>
          <Tr>
            <Td>
              <Skeleton  
              isLoaded={false}
              height='20px'
              ></Skeleton>
            </Td>  
            <Td>
              <Skeleton  
              isLoaded={false}
              height='20px'
              ></Skeleton>
            </Td>  
            <Td>
              <Skeleton  
              isLoaded={false}
              height='20px'
              ></Skeleton>
            </Td>  
            <Td>
              <Skeleton  
              isLoaded={false}
              height='20px'
              ></Skeleton>
            </Td>  
          </Tr> 
          <Tr>
            <Td>
              <Skeleton  
              isLoaded={false}
              height='20px'
              ></Skeleton>
            </Td>  
            <Td>
              <Skeleton  
              isLoaded={false}
              height='20px'
              ></Skeleton>
            </Td>  
            <Td>
              <Skeleton  
              isLoaded={false}
              height='20px'
              ></Skeleton>
            </Td>  
            <Td>
              <Skeleton  
              isLoaded={false}
              height='20px'
              ></Skeleton>
            </Td>  
          </Tr> 
          <Tr>
            <Td>
              <Skeleton  
              isLoaded={false}
              height='20px'
              ></Skeleton>
            </Td>  
            <Td>
              <Skeleton  
              isLoaded={false}
              height='20px'
              ></Skeleton>
            </Td>  
            <Td>
              <Skeleton  
              isLoaded={false}
              height='20px'
              ></Skeleton>
            </Td>  
            <Td>
              <Skeleton  
              isLoaded={false}
              height='20px'
              ></Skeleton>
            </Td>  
          </Tr>  
        </Tbody>
      </Table>
    </TableContainer>
    
    </Fragment>
  );
}